personal_web/urls.py
from django.contrib import admin
from django.urls import path
from personal.views import index, add_item

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('add', add_item, name='add')
]

personal/models.py
from django.db import models

# Create your models here.


class Item(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    done = models.BooleanField(null=False, blank=False, default=False)

    def __str__(self):
        return self.name

personal/views.py
from django.shortcuts import render, redirect
from .models import Item

# Create your views here.


def index(request):
    items = Item.objects.all()
    context = {
        'items': items
    }
    return render(request,'personal-web/index.html', context)

def add_item(request):
    if request.method == 'POST':
        name = request.POST.get('item_name')
        done = 'done' in request.POST
        Item.objects.create(name=name, done=done)

        return redirect('index')
    return render( request, 'personal-web/add_item.html' )

personal/templates/personal-web/add_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>add items</title>
</head>
<body>
    <h1>add a todo item</h1>

    <form action="POST" action="add">
        {% csrf_token %}
        <div>
            <p>
                <label for="id_name">Name:</label>
                <input type="text" id="id_name" name="item_name" />
            </p>
        </div>
        <div>
            <p>
                <label for="id_done">Done</label>
                <input type="checkbox" id="id_done" name="done" />
            </p>
        </div>
        <div>
            <p>
                <button type="submit">Add Item</button>
            </p>
        </div>
    </form>
</body>
</html>

personal/templates/personal-web/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>personal web</title>
</head>
<body>
    <h1>Document</h1>
    <table>
    {% for item in items %}
        <tr>
        {% if item.done %}
            <td><strike>{{ item.name }}</strike></td>
        {% else %}
            {{ item.name }}
        {% endif %}  
        </tr>
    {% empty %}
        <tr><td>you have nothing to do</td></tr>
    {% endfor %}
    </table>
    <a href="/add">Add an item</a>
</body>
</html>